# Generated by Django 4.2.6 on 2023-11-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0002_alter_userpayment_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='cvv_2',
            field=models.CharField(error_messages='Введите CVV', max_length=3, verbose_name='Код безопасности'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='email',
            field=models.EmailField(error_messages='Введите ваш email', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='expiration_date',
            field=models.CharField(error_messages='Срок действительности неверен', max_length=5, verbose_name='Срок действительности карты'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='phone_number',
            field=models.CharField(error_messages='Неверный номер', max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userpayment',
            name='username',
            field=models.CharField(error_messages='Введите ваше имя и фамилию', max_length=150, verbose_name='Имя владельца'),
        ),
    ]
