# Generated by Django 4.2.6 on 2023-11-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programm', '0003_alter_userpayment_cvv_2_alter_userpayment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpayment',
            name='card_number',
            field=models.CharField(error_messages='Неправильная карта', max_length=19, verbose_name='Номер карты'),
        ),
    ]
